// This file is autogenerated by VESC Tool

#ifndef RADS_CONFPARSER_H_
#define RADS_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		2968963463
#define SERIALIZED_CONFIG_LENGTH	248

// Functions
int32_t rads_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool rads_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void rads_confparser_set_defaults_main_config_t(main_config_t *conf);

// RADS_CONFPARSER_H_
#endif
