// This file is autogenerated by VESC Tool

#ifndef RABR_CONFPARSER_H_
#define RABR_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		3756683124
#define SERIALIZED_CONFIG_LENGTH	248

// Functions
int32_t rabr_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool rabr_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void rabr_confparser_set_defaults_main_config_t(main_config_t *conf);

// RABR_CONFPARSER_H_
#endif
