// This file is autogenerated by VESC Tool

#ifndef ECHO_CONFPARSER_H_
#define ECHO_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		2968963463
#define SERIALIZED_CONFIG_LENGTH	248

// Functions
int32_t echo_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool echo_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void echo_confparser_set_defaults_main_config_t(main_config_t *conf);

// ECHO_CONFPARSER_H_
#endif
